language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sjoshiftb/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true sjoshiftb/frontend npm run test

deploy:
    - provider: elasticbeanstalk
    - region: "ap-south-1"
    - app: "frontend"
    - env: "Frontend-env"
    - bucket_name: "elasticbeanstalk-ap-south-1-883199503448"
    - bucket_path: "frontend"
      on:
          branch: main
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: "$AWS_SECRET_KEY"
